package com.cm.gatecontroller.core.serial

sealed class Command(val value: String) {
    // Parameterless commands
    object RequestVersion : Command("AT+CONFIG=VERSION")
    object RequestGate : Command("AT+STGATE")
    object RequestLamp : Command("AT+STLAMP")
    object RequestLed : Command("AT+STLED")
    object RequestRelay1 : Command("AT+STRELAY1")
    object RequestRelay2 : Command("AT+STRELAY2")
    object RequestPhoto1 : Command("AT+STPHOTO1")
    object RequestPhoto2 : Command("AT+STPHOTO2")
    object RequestOpen1 : Command("AT+STOPEN1")
    object RequestOpen2 : Command("AT+STOPEN2")
    object RequestOpen3 : Command("AT+STOPEN3")
    object RequestOpen : Command("AT+STOPEN")
    object RequestClose1 : Command("AT+STCLOSE1")
    object RequestClose2 : Command("AT+STCLOSE2")
    object RequestClose3 : Command("AT+STCLOSE3")
    object RequestClose : Command("AT+STCLOSE")
    object RequestLoopA : Command("AT+STLOOPA")
    object RequestLoopB : Command("AT+STLOOPB")
    object RequestMainPower : Command("AT+STMPWR")
    object RequestTestCount : Command("AT+TESTCNT")
    object RequestDelayTime : Command("AT+STDELATTIME")
    object StartTest : Command("AT+TESTSTART")
    object StopTest : Command("AT+TESTSTOP")
    object RequestConfigLevelOpen : Command("AT+CONFIG=LEVELOPEN")
    object RequestConfigLevelClose : Command("AT+CONFIG=LEVELCLOSE")
    object RequestConfigLamp : Command("AT+CONFIG=LAMP")
    object RequestConfigBuzzer : Command("AT+CONFIG=BUZZER")
    object RequestConfigLampPosOn : Command("AT+CONFIG=LAMPPOSON")
    object RequestConfigLampPosOff : Command("AT+CONFIG=LAMPPOSOFF")
    object RequestConfigLedOpen : Command("AT+CONFIG=LEDOPEN")
    object RequestConfigLedOpenPos : Command("AT+CONFIG=LEDOPENPOS")
    object RequestConfigLedClose : Command("AT+CONFIG=LEDCLOSE")
    object RequestConfigLedClosePos : Command("AT+CONFIG=LEDCLOSEPOS")
    object RequestConfigLoopA : Command("AT+CONFIG=LOOPA")
    object RequestConfigLoopB : Command("AT+CONFIG=LOOPB")
    object RequestConfigDelayTime : Command("AT+CONFIG=DELAYTIME")
    object RequestConfigRelay1 : Command("AT+CONFIG=RELAY1")
    object RequestConfigRelay2 : Command("AT+CONFIG=RELAY2")
    object RequestPosition : Command("AT+STPOSITION")
    object FactoryReset : Command("AT+FACTORY")
    object OpenGateTest : Command("AT+OPEN")
    object CloseGateTest : Command("AT+CLOSE")

    // Parameterized commands
    data class SetOpenLevel(val level: Int) : Command("AT+SETLEVELOPEN=$level")
    data class SetCloseLevel(val level: Int) : Command("AT+SETLEVELCLOSE=$level")
    data class SetLampUsage(val state: String) : Command("AT+SETLAMP=$state")
    data class SetBuzzerUsage(val state: String) : Command("AT+SETBUZZER=$state")
    data class SetLampOnPosition(val state: String) : Command("AT+SETLAMPON=$state")
    data class SetLampOffPosition(val state: String) : Command("AT+SETLAMPOFF=$state")
    data class SetLedOpenColor(val color: String) : Command("AT+SETLEDOPEN=$color")
    data class SetLedOpenPosition(val state: String) : Command("AT+SETLEDOPENPOS=$state")
    data class SetLedCloseColor(val color: String) : Command("AT+SETLEDCLOSE=$color")
    data class SetLedClosePosition(val state: String) : Command("AT+SETLEDCLOSEPOS=$state")
    data class SetLoopAUsage(val state: String) : Command("AT+SETLOOPA=$state")
    data class SetLoopBUsage(val state: String) : Command("AT+SETLOOPB=$state")
    data class SetDelayTime(val time: Int) : Command("AT+SETDELAY=$time")
    data class SetRelay1Mode(val mode: Int) : Command("AT+SETRELAY1=$mode")
    data class SetRelay2Mode(val mode: Int) : Command("AT+SETRELAY2=$mode")
    data class SetControlLamp(val state: String) : Command("AT+CTRLLAMP=$state")
    data class SetControlRelay1(val state: String) : Command("AT+CTRLRELAY1=$state")
    data class SetControlRelay2(val state: String) : Command("AT+CTRLRELAY2=$state")
    data class SetControlLed(val color: String) : Command("AT+CTRLLED=$color")
}
